/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface BetterImgStencil {
      'alt': string;
      'fallback': string;
      'height': number;
      'log': string;
      'url': string;
      'width': number;
    }
  }

  interface HTMLBetterImgStencilElement extends StencilComponents.BetterImgStencil, HTMLStencilElement {}

  var HTMLBetterImgStencilElement: {
    prototype: HTMLBetterImgStencilElement;
    new (): HTMLBetterImgStencilElement;
  };
  interface HTMLElementTagNameMap {
    'better-img-stencil': HTMLBetterImgStencilElement;
  }
  interface ElementTagNameMap {
    'better-img-stencil': HTMLBetterImgStencilElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'better-img-stencil': JSXElements.BetterImgStencilAttributes;
    }
  }
  namespace JSXElements {
    export interface BetterImgStencilAttributes extends HTMLAttributes {
      'alt'?: string;
      'fallback'?: string;
      'height'?: number;
      'log'?: string;
      'url'?: string;
      'width'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;